# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true


jobs:
  # Single deploy job since we're just deploying
  directories: # Job that list subdirectories
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }} # generate output name dir by using inner step output
    steps:
      - uses: actions/checkout@v2
      - id: set-dirs # Give it an id to handle to get step outputs in the outputs key above
        run: echo "dir=$(ls -d */ | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
        # Define step output named dir base on ls command transformed to JSON thanks to jq
        
  build:
    runs-on: ubuntu-latest
    needs: [directories] # Depends on previous job
    strategy:
      matrix:
        dir: ${{fromJson(needs.directories.outputs.dir)}} # List matrix strategy from directories dynamically
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./${{matrix.dir}}
      - name: Build
        run: |
          cd ${{matrix.dir}}
          npm install
          npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ strategy.job-index }}
          path: ${{matrix.dir}}/dist
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs:
      - directories
      - build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - run: gh run download ${{ vars.GITHUB_RUN_ID }} --dir branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create public folder
        run: |
          mkdir public
          mv .github/workflows/index.html ./public/index.html
          cd public
          branches=$(echo '${{ needs.build_matrix.outputs.dir }}' | jq -r '.[]')
          i=0
          for branch in ${branches}
          do
            mkdir -p -- $branch
            mv ../$i/* ./$branch

            echo "<li><a href=\"./CV/${branch}\">${branch}</a></li>" >> index.html

            i=$((i+1))
          done
          cat ../.github/workflows/index_suffix.html >> index.html
          ls -lR
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
      
